# Generated by Django 5.2.8 on 2025-11-20 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional URL for the product image.', max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
