# Generated by Django 5.2.8 on 2026-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('beauty', 'Beauty'), ('home', 'Home & Garden'), ('sports', 'Sports'), ('food', 'Food & Groceries'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
