# Generated by Django 5.2.8 on 2026-02-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
