# Generated by Django 5.2.8 on 2026-02-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tin_number',
            field=models.CharField(blank=True, help_text='9-digit RRA TIN Number', max_length=9, null=True),
        ),
    ]
