# Generated by Django 5.2.8 on 2026-02-25 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_tin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SokohubCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sokohub_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sokohub Card',
                'verbose_name_plural': 'Sokohub Cards',
            },
        ),
    ]
