# Generated by Django 5.2.8 on 2026-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sokohubcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sokohubcard',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sokohubcard',
            name='virtual_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
