# Generated by Django 5.2.8 on 2026-02-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sokohubcard_card_number_sokohubcard_virtual_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sokohubcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
